FONTS = [
    'arial.ttf',
    'DejaVuSans.ttf',
    'LiberationSans-Regular.ttf',
]

SKILLS_AUTOCOMPLETE_LIMIT = 10
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
OPEN_STATUS = "open"
CLOSED_STATUS = "closed"
SKILL_NAME_MAX_LENGTH = 124
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
PROJECTS_PAGINATE_BY = 12
AVATAR_DEFAULT_SIZE = 128
AVATAR_FONT_SCALE = 0.6
AVATAR_FILENAME = 'avatar.png'
AVATAR_FORMAT = 'PNG'
AVATAR_TEXT_OFFSET_Y = -5

PASTEL_BLUE = '#A3C1DA'
PASTEL_MINT = '#B5D8B2'
PASTEL_ROSE = '#F7CAC9'
PASTEL_PEACH = '#F6E2B3'
PASTEL_AQUA = '#AED9E0'
PASTEL_LILAC = '#C3B1E1'
PASTEL_SUN = '#F9E79F'

PASTEL_COLORS = [
    PASTEL_BLUE,
    PASTEL_MINT,
    PASTEL_ROSE,
    PASTEL_PEACH,
    PASTEL_AQUA,
    PASTEL_LILAC,
    PASTEL_SUN,
]